### ISSUE TITLE
Encoder/Decoder break when encryption number + index of alph equal 57

### ISSUE THREAD

**Issue by andrew-fennell** [conroddy99/Message-Coder#1]
The encoder and decoder are exiting with "IndexError: list index out of range" when encryption number + index = 57.

To repeat the issue:

`Enter 1 to code a message or 2 do decode a message:1
Enter the text to be translated:Hello there, how are you?
Please enter your encryption number:3

4
3
4
3
4
3
4
3
4
3
4
3
Traceback (most recent call last):
  File "new encoder.py", line 280, in <module>
    print(tocode(text,cryptororiginal))
  File "new encoder.py", line 139, in tocode
    codedtext.append(alph[org(54,1,cryptor)])
IndexError: list index out of range`

**Comment by conroddy99** [comment]
Issue was resolved using 2770f2bcfcea10d253a58d8cac894403d8fb65c5
